"""Verify the _shellquote port matches real npm shell-quote (v1.8.1) output.

The fixture `tests/fixtures/shellquote_ground_truth.json` was generated by
running the actual shell-quote library under Node over a battery of inputs.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from claude_bash._shellquote import (
    has_malformed_tokens,
    has_shell_quote_single_quote_bug,
    parse,
    quote,
    try_parse_shell_command,
)

_FIXTURE = Path(__file__).parent / "fixtures" / "shellquote_ground_truth.json"
_CASES = json.loads(_FIXTURE.read_text())


@pytest.mark.parametrize("case", _CASES, ids=lambda c: f"{c['fn']}:{c['arg'][0][:24]!r}")
def test_matches_shell_quote_ground_truth(case):
    if case["fn"] == "quote":
        assert quote(case["arg"]) == case["result"]
    else:
        assert parse(case["arg"][0]) == case["result"]


# --- targeted unit checks -----------------------------------------------------


def test_quote_safe_chars_unquoted():
    assert quote(["/dev/null"]) == "/dev/null"
    assert quote(["plain"]) == "plain"


def test_quote_redirect_escaped():
    assert quote(["<"]) == "\\<"
    # `command` is a safe single word (unquoted); `<` is escaped to `\<` so it
    # becomes an eval argument rather than redirecting eval itself.
    assert quote(["command", "<", "/dev/null"]) == "command \\< /dev/null"


def test_quote_single_quote_switches_to_double():
    # A string containing ' goes to double-quote mode (the !-corruption path).
    assert quote(["it's"]) == '"it\'s"'


def test_parse_pipe_operator():
    assert parse("rg foo | wc -l") == ["rg", "foo", {"op": "|"}, "wc", "-l"]


def test_parse_glob():
    assert parse("ls *.py") == ["ls", {"op": "glob", "pattern": "*.py"}]


def test_parse_fd_redirect_tokens():
    assert parse("echo a 2>&1") == ["echo", "a", "2", {"op": ">&"}, "1"]


def test_parse_chained_operators():
    assert parse("a && b || c ; d") == [
        "a", {"op": "&&"}, "b", {"op": "||"}, "c", {"op": ";"}, "d",
    ]


def test_try_parse_success_and_failure():
    ok = try_parse_shell_command("echo hi | cat")
    assert ok.success and ok.tokens[0] == "echo"
    # Bad substitution should be caught and reported as failure.
    bad = try_parse_shell_command("echo ${}")
    assert bad.success is False


def test_has_shell_quote_single_quote_bug():
    # '\' — odd trailing backslash inside single quotes => bug.
    assert has_shell_quote_single_quote_bug(r"git ls-remote '\' 'repo'") is True
    # Plain single-quoted string => no bug.
    assert has_shell_quote_single_quote_bug("echo 'hello world'") is False


def test_has_malformed_tokens_unterminated_quote():
    cmd = 'echo "hi;evil | cat'  # one unmatched double quote
    parsed = parse(cmd)
    assert has_malformed_tokens(cmd, parsed) is True


def test_has_malformed_tokens_balanced_ok():
    cmd = "echo hello | cat"
    parsed = parse(cmd)
    assert has_malformed_tokens(cmd, parsed) is False
